version: '3.7'
services:
  vpncentralmanager:
    image: "jsenon/vpncentralmanager:latest"
    ports:
     - "9010:9010"
     - "50051:50051"
     - "7777:7777"
    environment:
    - AWS_ACCESS_KEY_ID=fakeMyKeyId
    - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    - AWS_DEFAULT_REGION=eu-central-1
    entrypoint: "./vpncentralmanager serve --url http://dynamoDB:8000"
  dynamoDB:
    image: "amazon/dynamodb-local"
    volumes:
      - ./db/:/data
    entrypoint: "java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    ports:
     - "8000:8000"