version: '3.7'
services:
  vpncentralmanager:
    image: "jsenon/vpncentralmanager:latest"
    ports:
     - "9010:9010"
     - "50051:50051"
     - "7777:7777"
    environment:
    - AWS_ACCESS_KEY_ID=faek
    - AWS_SECRET_ACCESS_KEY=fake
    - AWS_DEFAULT_REGION=eu-central-1
    entrypoint: "./vpncentralmanager serve --url http://dynamodb.eu-central-1.amazonaws.com --jaeger http://jaeger:14268 --debug"
  dynamoDB:
    image: "amazon/dynamodb-local"
    volumes:
      - ./db/:/data
    entrypoint: "java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    ports:
     - "8000:8000"
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411