apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpncentralmanager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpncentralmanager
      version: v.0.0.1
  template:
    metadata:
      labels:
        app: vpncentralmanager
        version: v.0.0.1
    spec:
      containers:
      - name: vpncentralmanager
        image: docker.io/jsenon/vpncentralmanager:latest
        command: ["./vpncentralmanager"]
        args: [serve,--url,http://localhost:8000]
        imagePullPolicy: Always